

#' This function generate the protein activity and store the protein activity in the
#' @param  seu The seu expression object
#' @species The species
#' @return  The seu results
#' @author Junqiang Wang
#' @export
SeuViperInternal<-function(seu, regulon){

  require(Seurat)
  require(viper)

  require(dplyr)

eset<-as.matrix(seu@assays$RNA@counts)

eset<-Log2CPM(eset)

#signarture is generated by z score transformation


tt <- t(scale(t(eset), center=TRUE, scale=TRUE))

sig<-na.omit(tt)

#sig<-viperSignature(eset=eset, ref=eset, method="zscore", bootstrap=FALSE)

pa<-viper(sig, regulon)

seu<-AddActivityAssay(seu, vp_mat=as.matrix(pa))

return(seu)

}



#' This function generate the protein activity and store the protein activity in the
#' @param  seu The seu expression object
#' @species The species
#' @return  The seu results
#' @author Junqiang Wang
#' @export
SeuViper<-function(seu,
                   regulon,
                   ref=NULL,
                   regression=FALSE,

                   Rank.transformation=FALSE,
                   sig.method=c( "viperSignature", "Z-transform", "RZ-transform"),
                    drop.na=c(TRUE,FALSE),
                     mvws=1){

  require(Seurat)
  require(viper)
  require(dplyr)
  require(tidyr)


  seu.assay.rna.counts.org<-seu@assays$RNA@counts %>% as.matrix()



  if(regression==FALSE){

    eset<-seu@assays$RNA@counts %>% as.matrix()


    if(is.null(ref)==TRUE){ ref<-eset}

    ref<-ref %>% as.matrix() %>% Log2CPM()

    eset<-eset %>% as.matrix() %>% Log2CPM()


# pre-process, re-oder the matrices
  overlapped.genes<-intersect(rownames(eset), rownames(ref))

  eset<-eset[match(overlapped.genes, rownames(eset)),]

  ref<-ref[match(overlapped.genes, rownames(ref)), ]


  #RT transformation

  if(Rank.transformation==TRUE){

 tt<-eset

  t2<- apply(tt, 2, rank)/(nrow(tt) + 1)

  t2q <- qnorm(t2)

  eset<-t2q



 tt<-ref

 t2<- apply(tt, 2, rank)/(nrow(tt) + 1)

  t2q <- qnorm(t2)

  ref<-t2q

  #sig<-t2q
}



  if(sig.method=="viperSignature"){

    sig<-viperSignature(eset=eset, ref=ref, method="zscore")

  }

  if(sig.method=="Z-transform"){

    ref.mean<-apply(ref, 1, mean)

    ref.sd<-apply(ref, 1, sd)

    sig<-apply(eset, 2, FUN=function(x){

      x<-(x-ref.mean)/ref.sd

     return(x)

    })

     sig<-na.omit(sig)

  }

  if (sig.method=="RZ-transform"){

    ref.mean<-apply(ref, 1, mean)

    ref.sd<-apply(ref, 1, sd)

    sig<-apply(eset, 2, FUN=function(x){

      x<-(x-ref.mean)/ref.sd

      return(x)

    })


    # tt<-eset

    tt<-sig


    t2<- apply(tt, 2, rank)/(nrow(tt) + 1)

    t2q <- qnorm(t2)

    sig<-t2q


    }

  }


 if(regression==TRUE){

  seu@active.assay<-'RNA'

  # run sctransform
  seu <- SCTransform(seu, vars.to.regress = "percent.mt", verbose = FALSE)

  eset<-as.matrix(seu@assays$SCT@scale.data)

  sig<-viperSignature(eset=eset, ref=eset, method="zscore")

  sig<-na.omit(sig)

 }



  pa<-viper(eset=sig, regulon=regulon, method="none", mvws=mvws)

  if(drop.na==TRUE){

    pa<-pa%>% as.matrix()%>% as.data.frame() %>% drop_na() %>% as.matrix()

  }else if(drop.na==FALSE){

    pa<-pa%>% as.matrix()%>% as.data.frame() %>% as.matrix()

  }

  seu@assays$RNA@counts<-seu.assay.rna.counts.org

  seu<-AddActivityAssay(seu, vp_mat=pa)


  return(seu)

}

















































































